---
title: "PAPER_6A"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
library(readr)
```

```{r}
spe = read10xVisium("~/data/sudmeier/750/")
rownames(spe) <- rowData(spe)$symbol
spe <- preprocess(spe, min_umi = 87)
spe = spacedeconv::normalize(spe)
```

```{r comparison2, collapse=TRUE, eval=TRUE}
metadata <- readr::read_tsv("~/data/TCR/IEDB_VDJDB_table_anno.tsv")
metadata$barcode <- paste0(metadata$barcode, "-1")
metadata <- metadata[metadata$Sample_x=="16", ]

pb <- progress::progress_bar$new(total = length(colnames(spe)))

TCRstat <- data.frame(row.names = colnames(spe))

for (spot in colnames(spe)){
  tmp <- metadata[metadata$barcode==spot, ]

  # IE Organism
  unknownIE <- tmp[tmp$Category_IEDB=="Unknown", ]
  otherIE <- tmp[tmp$Category_IEDB=="viral", ]
  sumUnknownIE <- sum(unknownIE$UMIs)
  sumOther <- sum(otherIE$UMIs)
  TCRstat[spot, "IEUnknown"] <- sumUnknownIE
  TCRstat[spot, "IEViral"] <- sumOther
  

  # VDJ
  unknownVDJ <- tmp[tmp$Category_VDJDB=="Unknown", ]
  otherVDJ <- tmp[tmp$Category_VDJDB=="viral", ]
  sumUnknownVDJ <- sum(unknownVDJ$UMIs)
  sumOtherVDJ <- sum(otherVDJ$UMIs)
  TCRstat[spot, "VDJUnknown"] <- sumUnknownVDJ
  TCRstat[spot, "VDJViral"] <- sumOtherVDJ
  
  pb$tick()
  
}

colData(spe) <- cbind(colData(spe), TCRstat)


pb$terminate()

ie <- plot_comparison(spe, cell_type_1 = "IEUnknown", cell_type_2 = "IEViral", density = F, smooth = F, title="IE Unknown vs Viral", palette = "Vik", reverse_palette = T, title_size = 25, spot_size = 1.03)
vdj <- plot_comparison(spe, cell_type_1 = "VDJUnknown", cell_type_2 = "VDJViral", density = F, smooth = F, title = "VDJUnknown vs Viral", palette = "Vik", title_size = 25, spot_size = 1.03, reverse_palette = T)
```



```{r}
tcr <- readRDS("~/export/paper/2Btcr.rds")
```

```{r}
tcr$UMIB0 <- colData(tcr)$UMITCR > 0
tcr$UMIB <- colData(tcr)$UMITCR >= 5

tcr <- preprocess(tcr, min_umi = 87)

tcr5 <- plot_celltype(tcr, cell_type = "UMIB", density = F, title = "TCR UMI > 5", smooth = F, show_image = T, palette = "Oslo", show_legend = F, zoom=TRUE, palette_type = "discrete", image_id = "hires", title_size = 25, spot_size = 1.03)
tcr0 <- plot_celltype(tcr, cell_type = "UMIB0", density = F, title = "TCR All", smooth = F, show_image = T, palette = "Oslo", show_legend = F, zoom=TRUE, palette_type = "discrete", image_id = "hires", title_size = 25, spot_size = 1.03)
tcrUMI <- plot_celltype(tcr, cell_type = "UMITCR", density = F, title = "TCR UMI", smooth = F, show_image = F, show_legend = T, zoom=TRUE, image_id = "hires", title_size = 25, spot_size = 1.03)
```

```{r, fig.width=15, fig.height=7}
library(gridExtra)

grid_layout <- rbind(c(1, 2, 3))

final <- grid.arrange(tcrUMI, tcr5, ie, layout_matrix=grid_layout)            
ggsave(filename = "~/exchange/spacedeconvPlots/6A_NEWTABLE.png", plot = final, dpi = 300)
```

