---
title: "PAPER 4B deconvolution"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, collapse=TRUE}
library(spacedeconv)
library(SpatialExperiment)
```

```{r spatialData}
spe = read10xVisium("~/data/cell2location/visium/48/")
rownames(spe) <- rowData(spe)$symbol
spe = preprocess(spe)
spe = spacedeconv::normalize(spe)
rownames(spe) <- make.names(rownames(spe), unique = T)
```

```{r referenceData}
sce = readRDS("~/data/cell2location/sce.rds")
rownames(sce) <- make.names(rownames(sce), unique = T) 
sce = sce[, !grepl("Unk", sce$annotation_1)]
sce = sce[, !grepl("LowQ", sce$annotation_1)]

sce = subsetSCE(sce, ncells = 20000, cell_type_col = "annotation_1")
```

```{r deconvC2L, fig.width=25, fig.height=15, collapse=TRUE}
sce = spacedeconv::normalize(sce)
signature = build_model(sce, cell_type_col = "annotation_1", method="cell2location", epochs = 250, gpu=T, batch_id_col="sample")
deconv = deconvolute(spe, method="cell2location", signature = signature, epochs = 30000, gpu=T, values = "relative")
saveRDS(deconv, file = "~/export/paper/PAPER_4B_C2L.rds")
```

```{r deconvRCTD, fig.width=25, fig.height=15, collapse=TRUE}
deconv = deconvolute(spe, method="rctd", single_cell_obj = sce, cell_type_col = "annotation_1", n_cores=8)
saveRDS(deconv, file = "~/export/paper/PAPER_4B_RCTD.rds")
```

