---
title: "Figure 4A Deconvolution"
author: "Constantin Zackl"
date: '2023-06-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(spacedeconv)
library(SpatialExperiment)
```

```{r spatialData}
spe = read10xVisium("~/data/maynard/")
rownames(spe) <- rowData(spe)$symbol

spe = preprocess(spe)

rownames(spe) <- make.names(rownames(spe), unique = T)
```

```{r referenceData}
sce = readRDS("~/data/brainAtlas/allenBrain.rds")
sce = subsetSCE(sce, cell_type_col = "subclass_label", ncells = 40000) 
sce$subclass_label <- make.names(sce$subclass_label)
```

```{r deconvolutionC2L, fig.width=15, fig.height=15, collapse=TRUE}
signature = build_model(sce, cell_type_col = "subclass_label", method="cell2location", epochs = 250, batch_id_col = "external_donor_name_label", gpu = T, assay_sc = "counts")
deconvC2L = deconvolute(spe, method = "cell2location", signature = signature, epochs = 30000, gpu=T, assay_sc = "counts", assay_sp = "counts")
saveRDS(deconvC2L, file = "~/export/paper/PAPER_4A_C2L.rds")
```