---
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
```

```{r}
deconvEstimate <- readRDS("~/export/paper/3AEstimate.rds")
deconvEPIC <- readRDS("~/export/paper/3AEpic.rds")
deconvQuanTiseq <- readRDS("~/export/paper/3AQuantiseq.rds")

title_size = 25
```

```{r}
estimate_tumor <- plot_celltype(deconvEstimate, cell_type = "estimate_tumor.purity", smooth = T, density = F, title="ESTIMATE Tumor Purity", title_size = title_size )
estimate_immune <- plot_celltype(deconvEstimate, cell_type = "estimate_immune.score", smooth = T, density = F, title="ESTIMATE Immune Score", title_size = title_size )
estimate_stroma <- plot_celltype(deconvEstimate, cell_type = "estimate_stroma.score", smooth = T, density = F, title="ESTIMATE Stroma Score", title_size = title_size )

```

```{r}
epic_caf <- plot_celltype(deconvEPIC, cell_type = "epic_Cancer.associated.fibroblast", smooth = TRUE, density = F, title = "EPIC CAFs", title_size = title_size)
epic_b <- plot_celltype(deconvEPIC, cell_type = "epic_B.cell", smooth = T, density = F, title = "EPIC B cells", title_size = title_size )
epic_endothelial <- plot_celltype(deconvEPIC, cell_type = "epic_Endothelial.cell", smooth = T, density = F, title = "EPIC Endothelial cell", title_size = title_size )
```

```{r}
quantiseq_cd8 <- plot_celltype(deconvQuanTiseq, cell_type = "quantiseq_T.cell.CD8.", density = F, smooth = T, title="quanTIseq CD8 T cells", title_size = title_size )
quantiseq_cd4 <- plot_celltype(deconvQuanTiseq, cell_type = "aggCD4", density = F, smooth = T, title="quanTIseq CD4+", title_size = title_size )
quantiseq_t <- plot_celltype(deconvQuanTiseq, cell_type = "aggT", density = F, smooth = T, title="quanTIseq T cells", title_size = title_size )
```

```{r plot, fig.width=19, fig.height=10}
library(gridExtra)
grid_layout <- rbind(c(1, 2, 3, 4), c(5, 6, 7, 8))

final = grid.arrange(estimate_tumor, estimate_immune, estimate_stroma, epic_caf, epic_b, epic_endothelial, quantiseq_t, quantiseq_cd8, layout_matrix = grid_layout)
ggsave(filename = "~/exchange/spacedeconvPlots/3A.png", plot = final, dpi = 300)
```



