---
title: "Figure 6B"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
```

```{r, collapse=TRUE}
spe = read10xVisium("~/data/renal/frozen_b1/")
```

```{r include=FALSE}
annot = read.csv("~/data/renal/frozen_b1/outs/spatial/GSM5924046_frozen_b_1_TLS_annotation.csv")

spe$tls <- annot$TLS_2_cat
```

```{r}
spe = preprocess(spe)
spe = spacedeconv::normalize(spe)
rownames(spe) = rowData(spe)$symbol
```

```{r fig.height=15, fig.width=15}
plot_celltype(spe, cell_type = "tls" ,offset_rotation = T, density=F, legend_size = 50, font_size = 30, palette = "BluYl", title="TLS")
```

```{r echo=FALSE}
deconv = deconvolute(spe, method = "quantiseq", assay_sp = "cpm", tumor=TRUE)
```

```{r, eval=FALSE}
deconv <- deconvolute(deconv, method = "mcp_counter", assay_sp = "cpm")
```

```{r include=FALSE, eval=FALSE}
ref = get_decoupleR_reference("progeny")
deconv = compute_activities(deconv, ref)

ref = get_decoupleR_reference("collectri")
deconv = compute_activities(deconv, ref)
```

```{r}
geneset = c("IGHA1", "IGHG1", "IGHG2", "IGHG3", "IGHG4", "IGHGP", "IGHM", "IGKG", "IGLC1", "IGLC2", "IGLC3", "JCHAIN", "CD79A", "FCRL5", "MZB1", "SSR4", "XBP1", "TRBC2", "IL7R", "CXCL12", "LUM", "C1QA", "C7", "CD52", "APOE", "PTLP", "PTGSD", "PIM2", "DERL3")
```

```{r}
deconv = gene_set_score(deconv, genes = geneset, assay="cpm")
```

```{r, eval=FALSE}
deconv = cluster(deconv, spmethod = "expression", clusres = 0.3)
```

```{r, eval=FALSE}
cluster <- plot_celltype(deconv, density = F, cell_type = "cluster_expression_res_0.3", offset_rotation = TRUE, title = "Cluster 0.3")
```

```{r}
patho <- plot_celltype(deconv, "tls", density = F, palette = "BluYl", offset_rotation = TRUE, title="Pathology annotation", title_size = 25, spot_size = 1.03)
geneSet <- plot_celltype(deconv, "geneSet", density = F, offset_rotation = TRUE, title = "TLS score", title_size = 25, spot_size = 1.03)
qBcells <- plot_celltype(deconv, "quantiseq_B.cell", density = F, offset_rotation = TRUE, smooth = TRUE, title = "quanTIseq B cells smoothed", title_size = 25, spot_size = 1.03)
```

```{r plot, fig.width=14.8, fig.height=5}
library(gridExtra)

grid_layout <- rbind(c(1, 2, 3))

final <- grid.arrange(patho, geneSet, qBcells,  layout_matrix = grid_layout)
ggsave(filename = "~/exchange/spacedeconvPlots/6B.png", plot = final, dpi = 300)
```

