---
title: "DensityAggregationSection1"
output: html_document
date: "2024-02-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
library(SpatialExperiment)
library(jsonlite)
library(purrr)
library(pbapply)
library(ggplot2)
library(spacedeconv)
```

```{r include=FALSE}
a1 <- read.table("./data/V1_Section1_detections.txt", sep = "\t", header = T)
```

```{r, collapse=TRUE}
spe = read10xVisium("~/data/breastCancer/Section1/outs/")
spe
```

```{r collapse=TRUE, include=FALSE}
coords = spatialCoords(spe)
head(coords)
```

```{r include=FALSE}
coords = spatialCoords(spe)
coords = as.data.frame(coords)
print (paste("Max X Cell Centroids: ", max(a1$Centroid.X.px)))
print (paste("Max Col Spot Coordinates: ", max(coords[, "pxl_col_in_fullres"])))
print (paste("Max Y: ", max(a1$Centroid.Y.px)))
print (paste("Max Row Spot Coordinates: ", max(coords[, "pxl_row_in_fullres"])))
print (paste("Number of cells: ", nrow(a1)))
```

```{r collapse=TRUE, include=FALSE}
scalefactors <- fromJSON("~/data/breastCancer/Section1/outs/spatial/scalefactors_json.json")

scalefactors
```

```{r collapse=TRUE, include=FALSE}
radius <- scalefactors$spot_diameter_fullres/2
radius
```

```{r collapse=TRUE, include=FALSE}
# function to calculate distance
calculate_distances <- function(spot_x, spot_y, cell_xs, cell_ys) {
  sqrt((spot_x - cell_xs)^2 + (spot_y - cell_ys)^2)
}

count_cells_within_radius <- function(spot_row, a1, radius) {
  spot_x <- spot_row$pxl_col_in_fullres 
  spot_y <- spot_row$pxl_row_in_fullres 
  
  # get all dsitances
  distances <- calculate_distances(spot_x, spot_y, a1$Centroid.X.px, a1$Centroid.Y.px)
  
  # count the ones inside the radius
  sum(distances <= radius)
}

```

```{r include=FALSE}
spe$cell_density <- unlist(pblapply(seq_len(nrow(coords)), function(i) count_cells_within_radius(coords[i, ], a1, radius), cl = 1))
```
```{r echo=FALSE}
plot_umi_count(spe)
plot_celltype(spe, cell_type = "cell_density")
```
```{r echo=FALSE}
print(paste("Mean Number of cells per spot:", mean(spe$cell_density)))
```


```{r include=FALSE}
deconv <- readRDS("~/data/allresults_minor_andersson.rds")
```

```{r include=FALSE}
deconv$cell_counts <- spe$cell_density
```

```{r include=FALSE}
for (result in available_results(deconv, "rctd")){
  deconv <- scale_cell_counts(deconv, result, "cell_counts")
}
```

```{r}
smooth = FALSE
```

```{r}
cutout <- subsetSPE(deconv, colRange = c(11200, 22000), rowRange = c(0, 15300))
```


```{r}
abs <- plot_celltype(spe, "cell_density", density = FALSE, title = "Cell counts", smooth = smooth, title_size = 25 )
cut <- plot_celltype(cutout, "cell_counts", density = FALSE, title = "Cell counts subset", smooth = smooth, title_size = 25 )
```

```{r}
xmin <- 270
xmax <- 510
ymin <- -380
ymax <- -90

library(sf)

# Define the coordinates of the rectangle
coords <- data.frame(x = c(xmin, xmax, xmax, xmin, xmin),
                     y = c(ymin, ymin, ymax, ymax, ymin))

abs <- abs +
  geom_polygon(data = coords, aes(x = x, y = y), 
               fill = NA, color = '#FF5733', size = 2, linetype = 'dashed') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())

print(abs)
```

```{r}
lumb <- plot_celltype(cutout, "rctd_Cancer.LumB.SC", density = F, title = "Cancer (LumB)", smooth = smooth, title_size = 25 )
lumbabs <- plot_celltype(cutout, "rctd_Cancer.LumB.SC_absolute", density = F, title = "Cancer (LumB) absolute", smooth = smooth, title_size = 25 )

caf <- plot_celltype(cutout, "rctd_CAFs.myCAF.like", density = F, title = "myCAFs", smooth = smooth, title_size = 25 )
cafabs <- plot_celltype(cutout, "rctd_CAFs.myCAF.like_absolute", density = F, title = "myCAFs absolute", smooth = smooth, title_size = 25 )

```


```{r echo=FALSE, fig.width=14}
library(gridExtra)

grid_layout <- rbind(c(1, 2, 3), c(4, 5, 6))
  
final <- grid.arrange(abs, lumb,  caf, cut, lumbabs, cafabs, layout_matrix=grid_layout)

ggsave(filename = "~/exchange/spacedeconvPlots/6C.png", plot = final, dpi = 300)
```
