---
title: "Paper Figure 4A"
author: "Constantin Zackl"
date: '2023-06-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(spacedeconv)
library(SpatialExperiment)
```

```{r}
deconv = readRDS("~/export/paper/PAPER_4A_C2L.rds")
# 151673
spatialLIBDAnnotation = readRDS("~/data/maynard/outs/spatial/spatial.rds")
```


```{r}
spatialLIBDAnnotation = filter_sample_id(spatialLIBDAnnotation, "151673")
groundTruth = spatialLIBDAnnotation$spatialLIBD
deconv$groundTruth = groundTruth
```


```{r, fig.width=22, fig.height=20}
truth <- plot_celltype(deconv, cell_type = "groundTruth", density = F, smooth = F, title = "Ground truth (human)", show_image = F, palette="Inferno", title_size = 25 )
l5 <- plot_celltype(deconv, "cell2location_L5.IT", density = F, smooth = T, title = "L5.IT C2L", title_size = 25 )
l6 <- plot_celltype(deconv, "cell2location_L2.3.IT", density = F, smooth = T, title = "L2.3.IT C2L", title_size = 25 )
oligo <- plot_celltype(deconv, "cell2location_Oligo", density = F, smooth = T, title = "Oligodendrocytes C2L", title_size = 25 )
astro <- plot_celltype(deconv, "cell2location_Astro", density = F, smooth = T, title = "Astrocytes", title_size = 25 )
```

```{r, fig.width=15, fig.height=10}
cluster <- cluster(deconv, spmethod="expression", clusres = c(0.2, 0.25, 0.3, 0.4, 0.45, 0.5))
plot_celltype(cluster, "cluster", palette = "inferno", density = F)
cluster <- cluster(deconv, spmethod="cell2location", ncluster= 7, method="kmeans", dist_method="euclidean")
kmeans_7 = plot_celltype(cluster, "cluster_cell2location_nclusters_7", palette = "Accent", density = F, title = "k-means C2L 7", title_size = 25 )
kmeans_8 = plot_celltype(cluster, "cluster_cell2location_nclusters_8", palette = "Accent", density = F, title = "k-means C2L 8", title_size = 25 )
```
```{r, fig.width=6, fig.height=5}
library(ggplot2)
mAbundant <- plot_most_abundant(deconv, method = "cell2location", min_abundance = 0.1, min_spot =200,   remove = "cell2location_Endo", title = "Most Abundant C2L", title_size = 25 ) +scale_fill_manual(values = colorspace::sequential_hcl(4, "viridis"), labels = c("Astro", "L2.3.IT", "L5.IT", "Oligo"))
                                                                                                                                                                                        
```


```{r, fig.width=15, fig.height=10}
library(decoupleR)

ref <- get_decoupleR_reference(method="collectri")
res <- spacedeconv::normalize(cluster)
res <- compute_activities(res, assay = "cpm", method="wmean", reference = ref)


ref <- get_decoupleR_reference(method="dorothea")
res <- compute_activities(res, assay = "cpm", method="wmean", reference = ref)

res <- cluster(res,  spmethod="cell2location", method="kmeans", ncluster = 3:8, dist_method="euclidean")
```



```{r, fig.width=16, fig.height=10}
library(gridExtra)

grid_layout <- rbind(c(1, 2, 3), c(4, 5, 6))

final <- grid.arrange(truth, kmeans_7, mAbundant, oligo, l5, l6, layout_matrix = grid_layout)
ggsave(filename = "~/exchange/spacedeconvPlots/4A.png", plot = final, dpi = 300)
```
