---
title: "Fig 3A Deconvolution"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
```

```{r data, collapse=TRUE}
spe = read10xVisium("~/data/sudmeier/750/")
```

```{r preprocessing, collapse=TRUE}
rownames(spe) <- rowData(spe)$symbol
spe <- preprocess(spe, min_umi = 87) # remove low count spots
spe = spacedeconv::normalize(spe)
```

```{r tcrMetadata, collapse=TRUE}
metadata <- read.csv("../data/IEDB_VDJDB_table_anno.tsv", sep = "\t")

# filter only TCR clonotype
metadata <- dplyr::filter(metadata, grepl("TRB", metadata$Clonoytpe_ids))
metadata$barcode <- paste0(metadata$barcode, "-1")

metadata$Clonoytpe_ids <- make.names(metadata$Clonoytpe_ids)
metadata <- metadata[metadata$Sample=="16", ] # patient 16

# add metadata to object
for (clonotype in unique(metadata$Clonoytpe_ids)){
  tmp <- metadata[metadata$Clonoytpe_ids==clonotype, ]
  spe <- annotate_spots(spe, tmp$barcode, name = clonotype)
}
```

```{r, collapse=TRUE}
deconvEstimate = deconvolute(spe, method="estimate", assay_sp = "cpm")
saveRDS(deconvEstimate, file = "~/export/paper/3AEstimate.rds")
```

```{r, collapse=TRUE}
deconvEPIC = deconvolute(spe, method="epic", assay_sp = "cpm", tumor=TRUE)
saveRDS(deconvEPIC, file = "~/export/paper/3AEpic.rds")
```

```{r, collapse=TRUE}
deconvQuanTiseq = deconvolute(spe, method="quantiseq", assay_sp = "cpm", tumor=TRUE)

deconvQuanTiseq <- aggregate_results(deconvQuanTiseq, cell_type_1 = "quantiseq_T.cell.CD4...non.regulatory.", cell_type_2 = "quantiseq_T.cell.regulatory..Tregs.", name = "aggCD4")
deconvQuanTiseq <- aggregate_results(deconvQuanTiseq, cell_type_1 = "aggCD4", cell_type_2 = "quantiseq_T.cell.CD8.", name = "aggT")

saveRDS(deconvQuanTiseq, file = "~/export/paper/3AQuantiseq.rds")
```

```{r}
plot_celltype(deconvEstimate, cell_type = "estimate_tumor.purity", smooth = T, density = F, title="Estimate Tumor Purity")
plot_celltype(deconvEstimate, cell_type = "estimate_immune.score", smooth = T, density = F, title="Estimate Immune Score")
plot_celltype(deconvEstimate, cell_type = "estimate_stroma.score", smooth = T, density = F, title="Estimate Stroma Score")
```

```{r}
plot_celltype(deconvEPIC, cell_type = "epic_Cancer.associated.fibroblast", smooth = TRUE, density = F, title_size = 12, title = "EPIC Cancer Associated Fibroplast")
plot_celltype(deconvEPIC, cell_type = "epic_B.cell", smooth = F, density = F, title_size = 12, title = "EPIC B cells unsmoothed")
plot_celltype(deconvEPIC, cell_type = "epic_B.cell", smooth = T, density = F, title_size = 12, title = "EPIC B cells smoothed")
```

```{r}
plot_celltype(deconvQuanTiseq, cell_type = "quantiseq_T.cell.CD8.", density = F, smooth = T, title="quanTIseq CD8+")
plot_celltype(deconvQuanTiseq, cell_type = "aggCD4", density = F, smooth = T, title="quanTIseq CD4+")
plot_celltype(deconvQuanTiseq, cell_type = "aggT", density = F, smooth = T, title="quanTIseq T cells")
```

