---
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
```

```{r loadData}
decouple <- readRDS("~/export/paper/2BdecoupleR.rds")
tcr <- readRDS("~/export/paper/2Btcr.rds")

title_size = 25
```

```{r}
tgfb <- plot_celltype(decouple, cell_type = "progeny_TGFb", title = "TGFb", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
wnt <- plot_celltype(decouple, cell_type = "progeny_WNT", title = "WNT", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
hypox <- plot_celltype(decouple, cell_type = "progeny_Hypoxia", title = "Hypoxia", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
myc <- plot_celltype(decouple, cell_type = "collectri_MYC", title = "MYC", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
jak <- plot_celltype(decouple, cell_type = "progeny_JAK.STAT", title = "JAK-STAT", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
stat <- plot_celltype(decouple, cell_type = "collectri_STAT1", title = "STAT1", density = F, smooth = T, title_size = title_size, spot_size = 1.03)
```


```{r}

tcr$UMIB0 <- colData(tcr)$UMITCR > 0
tcr$UMIB <- colData(tcr)$UMITCR >= 5

tcr <- preprocess(tcr, min_umi = 87)

tcr5 <- plot_celltype(tcr, cell_type = "UMIB", density = F, title = "TCR", smooth = F, show_image = T, palette = "Oslo", show_legend = F, zoom=TRUE, palette_type = "discrete", image_id = "hires", title_size = title_size, spot_size = 1.03)

```

```{r}
spe = read10xVisium("~/data/sudmeier/750/")
rownames(spe) <- rowData(spe)$symbol
spe = subsetSPE(spe, colRange = c(0, 10000))
spe = spacedeconv::normalize(spe)
```

```{r comparison2, collapse=TRUE, eval=FALSE}
# ORGANISM 
metadata <- read.csv("~/data/TCR/Spatial_final_table_TRB.csv")
metadata$barcode <- paste0(metadata$barcode, "-1")
metadata <- metadata[metadata$Sample=="16", ]

pb <- progress::progress_bar$new(total = length(colnames(spe)))
TCRstat <- data.frame(row.names = colnames(spe))

for (spot in colnames(spe)){
  tmp <- metadata[metadata$barcode==spot, ]

  #print (tmp)
  
  # IE Organism
  unknownIE <- tmp[tmp$IEDB_organism=="Unknown", ]
  otherIE <- tmp[tmp$IEDB_organism!="Unknown", ]
  sumUnknownIE <- sum(unknownIE$UMIs)
  sumOther <- sum(otherIE$UMIs)
  TCRstat[spot, "IEUnknown"] <- sumUnknownIE
  TCRstat[spot, "IEOther"] <- sumOther
  

  # VDJ
  unknownVDJ <- tmp[tmp$VDJDB_organism=="Unknown", ]
  otherVDJ <- tmp[tmp$VDJDB_organism!="Unknown", ]
  sumUnknownVDJ <- sum(unknownVDJ$UMIs)
  sumOtherVDJ <- sum(otherVDJ$UMIs)
  TCRstat[spot, "VDJUnknown"] <- sumUnknownVDJ
  TCRstat[spot, "VDJOther"] <- sumOtherVDJ
  
  pb$tick()
  
}

colData(spe) <- cbind(colData(spe), TCRstat)

pb$terminate()

plot_comparison(spe, cell_type_1 = "IEUnknown", cell_type_2 = "IEOther", density = F, smooth = T, title="IEUnknown/IEOther", palette = "Vik", title_size = title_size, spot_size = 1.03)
vdj <- plot_comparison(spe, cell_type_1 = "VDJUnknown", cell_type_2 = "VDJOther", density = F, smooth = F, title = "Unknown TCR", palette = "Vik", title_size = title_size, spot_size = 1.03)
```

```{r, fig.width=15, fig.height=15, eval=FALSE}
plot_comparison(spe, cell_type_1 = "VDJUnknown", cell_type_2 = "VDJOther", density = F, smooth = F, title = "TCR unknown vs. db", palette = "Vik", legend_size = 40, title_size = 50, font_size = 30, title_size = title_size, spot_size = 1.03)


plot_celltype(spe, cell_type = "VDJUnknown", density = F, limits = c(0, 15))
plot_celltype(spe, cell_type = "VDJOther", density = F)
```




```{r cluster}
deconvEPIC <- readRDS("~/export/paper/3Bepic.rds")
deconvQuanTIseq <- readRDS("~/export/paper/3Bquantiseq.rds")

deconvQuanTIseq = deconvQuanTIseq[!duplicated(rownames(deconvQuanTIseq)), ]

cluster1 <- cluster(deconvQuanTIseq, data = "expression", clusres = 0.1)
cluster2 <- cluster(deconvQuanTIseq, data = "expression", clusres = 0.2)
cluster3 <- cluster(deconvQuanTIseq, data = "expression", clusres = 0.3)

clusterX <- cluster(deconvEPIC, spmethod = "epic", nclusters = 3)


pclus1 <- plot_celltype(cluster1, "cluster", palette = "Accent", title = "Clustering 0.1", density = F, title_size = title_size, spot_size = 1.03)
pclus2 <- plot_celltype(cluster2, "cluster", palette = "inferno", title = "Clustering 0.2", density = F, title_size = title_size, spot_size = 1.03)
pclus3 <- plot_celltype(cluster3, "cluster", palette = "Accent", title = "Clustering 0.3", density = F, title_size = title_size, spot_size = 1.03)
plot_celltype(clusterX, "cluster", palette = "inferno", title = "Clustering EPIC", density = F, title_size = title_size, spot_size = 1.03)

```

```{r, fig.width=15, fig.height=15}
mAbundantSTD <- plot_most_abundant(deconvEPIC, method="epic", palette = "inferno", legend_size = 30, font_size = 20, min_abundance = 0.05, title = "Most Abundant", title_size = title_size, spot_size = 1.03) 
mAbundantNoCancer <- plot_most_abundant(deconvEPIC, method="epic", palette = "inferno", legend_size = 30, font_size = 20, remove = "epic_uncharacterized.cell", min_abundance = 0.05, title="Without Tumor", title_size = title_size, spot_size = 1.03)

mAbundantSTD = mAbundantSTD + ggplot2::scale_fill_manual(values = RColorBrewer::brewer.pal(7, "Accent"), labels=c("B cells", "CAFs", "Endothelial", "Macrophage", "CD4", "CD8", "Tumor"))
mAbundantSTD 
mAbundantNoCancer = mAbundantNoCancer + ggplot2::scale_fill_manual(values = c(RColorBrewer::brewer.pal(6, "Accent"),  "#D3D3D3"), labels=c("B cells", "CAFs", "Endothelial", "Macrophage", "CD4", "CD8", "Undefined"))
mAbundantNoCancer
```


```{r}
spe <- get_lr(spe, resource = "Consensus", method = "min", organism = "human")
```

```{r}
col <- plot_celltype(spe, "lr_COL18A1.ITGB1", density = FALSE, smooth = T, title = "COL18A1-ITGB1", title_size = title_size, spot_size = 1.03)
```


```{r plot, fig.width=17, fig.height=15}
library(gridExtra)

grid_layout <- rbind(c(1, 2, 3, 4), c(5, 6, 7, 8), c(9, 9, 10, 10))

tmp = grid.arrange(wnt, hypox, myc, tgfb, jak, col, pclus1,  pclus3, mAbundantSTD, mAbundantNoCancer, layout_matrix = grid_layout)

ggsave(filename = "~/exchange/spacedeconvPlots/3B.png", plot = tmp, dpi=300)
```
