---
title: "Fig 5A"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
library(colorspace) 
library(scales)   
library(gtable)
```


```{r}
combine_runs <- function(method_name, runs) {
  combined_orig <- data.frame()
  combined_mirror <- data.frame()
  combined_even <- data.frame()

  for (run in runs) {
    orig <- readRDS(paste0("~/export/subset2/results/orig/deconv_", method_name, "_orig.rds"))
    mirror <- readRDS(paste0("~/export/subset2/results/run", run, "/deconv_", method_name, "_mirror_run", run, ".rds"))
    even <- readRDS(paste0("~/export/subset2/results/run", run, "/deconv_", method_name, "_even_run", run, ".rds"))

    df_orig <- as.data.frame(colData(orig)[available_results(orig)])
    df_mirror <- as.data.frame(colData(mirror)[available_results(mirror)])
    df_even <- as.data.frame(colData(even)[available_results(even)])

    combined_orig <- rbind(combined_orig, df_orig)
    combined_mirror <- rbind(combined_mirror, df_mirror)
    combined_even <- rbind(combined_even, df_even)
  }

  return(list(orig = combined_orig, mirror = combined_mirror, even = combined_even))
}
```


```{r}
correlation_data <- read.csv("~/export/subset2/results/correlation_results.csv")

correlation_data$Method <- as.factor(correlation_data$Method)

deconv_data <- correlation_data %>%
  filter(Type %in% c("mirror", "even", "mirror_deconv", "even_deconv"))

deconv_data$Type <- factor(ifelse(deconv_data$Type %in% c("mirror_deconv", "mirror"), "mirror", "even"))

fill_colors <- RColorBrewer::brewer.pal(3, "Set3")[2:3] 
border_colors <- darken(fill_colors, amount = 0.2)    

deconv_boxplot <- ggplot(deconv_data, aes(x = Method, y = Correlation, fill = Type)) +
  geom_boxplot(aes(color = Type), size = 0.5) +  
  theme_minimal() +
  labs(title = "Deconvolution Correlation Across Methods",
       y = "Correlation",
       fill = "Subset Type") +  
  scale_fill_manual(values = fill_colors) +  
  scale_color_manual(values = border_colors) +  
  scale_x_discrete(labels = c("CARD", "cell2location", "RCTD", "spatialDWLS", "SPOTlight")) +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())

cell2location_data <- combine_runs("cell2location", 1:10)
rctd_data <- combine_runs("rctd", 1:10)

rctdMirror = plot_scatter_df(rctd_data$orig, rctd_data$mirror, color_palette = "Set3", title = "RCTD (mirror)", x = "Original", y = "Mirror", point_alpha = 1)
rctdEven = plot_scatter_df(rctd_data$orig, rctd_data$even, color_palette = "Set3", title = "RCTD (even)", x = "Original", y = "Even", point_alpha = 1)
cell2locationEven = plot_scatter_df(cell2location_data$orig, cell2location_data$even, color_palette = "Set3", title = "cell2location (even)", x = "Original", y = "Even", point_alpha = 1)
cell2locationMirror = plot_scatter_df(cell2location_data$orig, cell2location_data$mirror, color_palette = "Set3", title = "cell2location (mirror)", x = "Original", y = "Mirror", point_alpha = 1)


rctdMirror = rctdMirror + scale_color_manual(values=RColorBrewer::brewer.pal(9, "Set3"), labels=c("B cells", "CAFs", "Cancer Epithelial", "Endothelial", "Myeloid", "Normal Epithelial", "Plasmablasts", "PVL", "T cells"))

scatter_legend <- get_legend(
  rctdMirror + 
  guides(color = guide_legend(title = NULL, nrow = 1, byrow = TRUE)) +  
  theme(
    legend.key.size = unit(0.3, "cm"),
    legend.text = element_text(size = 10)
  )
)

boxplot_legend <- get_legend(
  deconv_boxplot + 
  guides(fill = guide_legend(title=NULL, nrow = 1, byrow=TRUE)) +  
  theme(
    legend.key.size = unit(0.8, "cm"),
    legend.text = element_text(size = 12)
  )
)

boxplot_legend_cleaned <- boxplot_legend[-3]

rctdMirror <- rctdMirror + theme(legend.position = "none")
rctdEven <- rctdEven + theme(legend.position = "none")
cell2locationEven <- cell2locationEven + theme(legend.position = "none")
cell2locationMirror <- cell2locationMirror + theme(legend.position = "none")
deconv_boxplot <- deconv_boxplot + theme(legend.position = "none")

deconv_boxplot <- deconv_boxplot + 
  theme(
    plot.title = element_blank(),  
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 12)    
  )

rctdMirror <- rctdMirror + 
  theme(
    plot.title = element_text(size = 16, face = "bold"),  
    axis.title = element_text(size = 14), 
    axis.text = element_text(size = 12)   
  )

rctdEven <- rctdEven + 
  theme(
    plot.title = element_text(size = 16, face = "bold"), 
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 12)    
  )

cell2locationEven <- cell2locationEven + 
  theme(
    plot.title = element_text(size = 16, face = "bold"), 
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 12)    
  )

cell2locationMirror <- cell2locationMirror + 
  theme(
    plot.title = element_text(size = 16, face = "bold"),  
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 12)    
  )

final_layout <- grid.arrange(
  deconv_boxplot,  
  rctdMirror, rctdEven, cell2locationMirror, cell2locationEven, 
  boxplot_legend_cleaned, scatter_legend ,  
  layout_matrix = rbind(
    c(1, 1, 2, 3),
    c(1, 1, 4, 5),
    c(6, 6, 7, 7) 
  ),
  heights = c(5, 5, 1)
)

ggsave(filename = "~/export/subset2/plots/fig_5AB.png", plot = final_layout, dpi = 300, width = 16, height = 10)

```
