---
title: "Fig 5 CD"
output: html_document
date: "`r Sys.Date()`"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
library(ggplot2)
library(grid)
library(gridExtra)
```
```{r,   fig.width=10, fig.dpi=300, fig.width=10}
library(corrplot)
library(multimode)
library(psych)
```
Fig 5C
```{r,   fig.width=10, fig.dpi=300, fig.width=10}
major_c2l_andersson <- readRDS("~/data/major_c2l_andersson.rds")
column_names <- colnames(colData(major_c2l_andersson))
new_column_names <- sub("c2l", "cell2location", column_names)
colnames(colData(major_c2l_andersson)) <- new_column_names
```

```{r}
rctd_spatialdwls_major_andersson <- readRDS("~/data/rctd_spatialdwls_major_andersson.rds")
```

```{r}
c2l_results <- colData(major_c2l_andersson)
colData(rctd_spatialdwls_major_andersson) <- cbind(colData(rctd_spatialdwls_major_andersson), c2l_results)
var_deconv <- available_results(rctd_spatialdwls_major_andersson)
```

```{r, fig.width=25, fig.dpi=400, fig.width=25}
png(file = "~/export/Fig5/test2_highres4_square_number_purpleorange.png",
    res = 600,
    width = 10000,
    height = 10000)
spatialcorr(spe = rctd_spatialdwls_major_andersson,
                   adjust = "bonferroni",
                   method = var_deconv,
                   sig.level = c(0.001, 0.01, 0.05),
                   type = "full",
                   diag = TRUE,
                   order = "hclust",
                   plot_layout = "color", 
                   insig = "blank",
                   addCoef.col = "black",
                   number.digits = 2,
                   col = COL2("PuOr"),
                   tl.cex = 1.7, cl.cex = 1.4)
dev.off()
```
Fig 5D
```{r}
rctd_spatialdwls_major_andersson <- readRDS("~/data/rctd_spatialdwls_major_andersson.rds")
major_c2l_andersson <- readRDS("~/data/major_c2l_andersson.rds")
test <- colData(major_c2l_andersson)
test <- test[, !(colnames(test) %in% c("in_tissue", "array_row", "array_col", "sample_id"))]
column_names <- colnames(colData(major_c2l_andersson))
column_names <- colnames(test)
new_column_names <- sub("c2l", "cell2location", column_names)
colnames(test) <- new_column_names
colData(major_c2l_andersson) <- test
c2l_results <- colData(major_c2l_andersson)
colData(rctd_spatialdwls_major_andersson) <- cbind(colData(rctd_spatialdwls_major_andersson), c2l_results)
spe_final <- rctd_spatialdwls_major_andersson
```
CAFS
```{r}
a <- spacedeconv::plot_scatter(spe1 = spe_final,
             value1 = "spatialdwls_CAFs",
             spe2 = spe_final,
             value2 = "rctd_CAFs",
             title = "")
final <- a +
    theme_minimal(base_size = 20) +
    theme(
      plot.title = element_text(size = 20, face = "bold"),
      axis.title = element_text(size = 20),
      axis.text = element_text(size = 20)) 
  
ggsave("~/export/scatter_1.png", plot = final, dpi = 600, width = 7, height = 6)
b <- spacedeconv::plot_scatter(spe1 = spe_final,
             value1 = "spatialdwls_CAFs",
             spe2 = spe_final,
             value2 = "cell2location_CAFs", 
             title = "")
final2 <- b +
    theme_minimal(base_size = 20) +
    theme(
      plot.title = element_text(size = 20, face = "bold"),
      axis.title = element_text(size = 20),
      axis.text = element_text(size = 20)) 
  
ggsave("~/export/scatter_2.png", plot = final2, dpi = 600, width = 7, height = 6)
c <- spacedeconv::plot_scatter(spe1 = spe_final,
             value1 = "rctd_CAFs",
             spe2 = spe_final,
             value2 = "cell2location_CAFs",
             title = "")
final3 <- c +
    theme_minimal(base_size = 20) +
    theme(
      plot.title = element_text(size = 20, face = "bold"),
      axis.title = element_text(size = 20),
      axis.text = element_text(size = 20)) 
  
ggsave("~/export/scatter_3.png", plot = final3, dpi = 600, width = 7, height = 6)
```