---
title: "Fig 3B Deconvolution"
author: "Constantin Zackl"
date: "`r Sys.Date()`"
output: html_document
---
 


```{r}
library(spacedeconv)
library(SpatialExperiment)
library(decoupleR)
```

```{r data, collapse=TRUE}
spe = read10xVisium("~/data/sudmeier/750/")
```

```{r preprocessing, collapse=TRUE}
rownames(spe) <- rowData(spe)$symbol
spe <- preprocess(spe, min_umi = 87) # remove low count cells
spe = spacedeconv::normalize(spe)
```

```{r tcrMetadata, collapse=TRUE}
metadata <- read.csv("~/data/TCR/Spatial_final_table.tsv", sep = "\t")

# filter only TCR clonotype
metadata <- dplyr::filter(metadata, grepl("TRB", metadata$Clonoytpe_ids))
metadata$barcode <- paste0(metadata$barcode, "-1")
metadata$Clonoytpe_ids <- make.names(metadata$Clonoytpe_ids)
metadata <- metadata[metadata$Sample=="16", ]

# add metadata to object
for (clonotype in unique(metadata$Clonoytpe_ids)){
  tmp <- metadata[metadata$Clonoytpe_ids==clonotype, ]
  spe <- annotate_spots(spe, tmp$barcode, name = clonotype)
}
```


```{r}
ref <- get_decoupleR_reference("progeny")
deconv <- compute_decoupleR_activities(spe, ref)
ref <- get_decoupleR_reference("collectri")
deconv <- compute_decoupleR_activities(deconv, ref)


saveRDS(deconv, file = "~/export/paper/3BdecoupleR.rds")

```

```{r}
plot_celltype(deconv, cell_type = "progeny_TGFb", smooth = T, density = F, title="TGFb")
plot_celltype(deconv, cell_type = "progeny_WNT", smooth = T, density = F, title="WNT")

plot_celltype(deconv, cell_type = "collectri_BATF", smooth = T, density = F, title="BATF")
plot_celltype(deconv, cell_type = "collectri_EOMES", smooth = T, density = F, title="EOMES")
```



```{r plotTCRUMI, collapse=TRUE, fig.width=15}

speTCR = read10xVisium("~/data/sudmeier/750/", images = "hires")

rownames(speTCR) <- rowData(speTCR)$symbol
for (spot in colnames(speTCR)){
  tmp <- metadata[metadata$barcode==spot, ]
  umi <- sum(tmp$UMIs)
  colData(speTCR)[spot, "UMITCR"] <- umi
}

saveRDS(speTCR, file = "~/export/paper/3Btcr.rds")

plot_celltype(speTCR, cell_type = "UMITCR", density = F, title = "TCR UMI", smooth = T, show_image = F)

speTCR$UMIB <- colData(speTCR)$UMITCR >= 5

plot_celltype(speTCR, cell_type = "UMIB", density = F, title = "TCR UMI >= 5", smooth = F, show_image = T, palette = "Oslo")

```


```{r, collapse=TRUE}
spe = read10xVisium("~/data/sudmeier/750/")
rownames(spe) <- rowData(spe)$symbol
spe <- preprocess(spe, min_umi = 87)
spe = spacedeconv::normalize(spe)
```

```{r deconv2, collapse=TRUE}
deconvEPIC <- deconvolute(spe, method = "epic", assay_sp = "cpm", tumor=TRUE)
deconvQuanTIseq <- deconvolute(spe, method="quantiseq", assay_sp = "cpm", tumor=TRUE)

saveRDS(deconvEPIC, file = "~/export/paper/3Bepic.rds")
saveRDS(deconvQuanTIseq, file = "~/export/paper/3Bquantiseq.rds")
```

