---
title: "Suppl Fig 2"
output: html_document
date: '2024-02-15'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(spacedeconv)
library(SpatialExperiment)
library(ggplot2)
library(grid)
```

```{r}
spe_expre_andersson_0.2 <- readRDS("~/data/spe_expre_andersson_0.2.rds")
```

```{r, fig.width=15, fig.height=15}
clus <- spacedeconv::plot_celltype(spe_expre_andersson_0.2, 
                                   cell_type = "cluster_expression_0.2",
                                   palette = "Dark2",
                                   density = F,
                                   title = "Clustering 0.2",
                                   title_size = 40,
                                   font_size = 30,
                                   legend_size = 30)
clus
ggsave("~/export/suppl_2_clustering.png", plot = clus, dpi = 300, height = 15, width = 15)
```

```{r, clustering plot}
spe_object <- readRDS("~/data/major_c2l_andersson.rds")
```

```{r}
column_names <- colnames(colData(spe_object))
new_column_names <- sub("c2l", "cell2location", column_names)
colnames(colData(spe_object)) <- new_column_names
```

```{r, fig.width=15, fig.height=15}
custom_colors_hex_1 <- c("#fa6607", "#507f89", "#aec3b0", "#fdeca0", "#e7c590", "#e1ceff")
#"B cells", "Cancer Epithelial", "Endothelial", "Normal Epithelial", "PVL", "T cells")
x <- spacedeconv::plot_most_abundant(spe_object, method = "cell2location",
                                density = FALSE,
                                palette = "Set2",
                                title = "Most Abundant",
                                min_spot = 10,
                                title_size = 40,
                                font_size = 30,
                                legend_size = 30)

x <- x + ggplot2::scale_fill_manual(values = custom_colors_hex_1,
                                    labels=c("B cells", "Cancer Epithelial", "Endothelial", "Normal Epithelial", "PVL", "T cells"))
ggsave("~/export/suppl_2_mostAbundant.png", plot = x, dpi = 300, height = 15, width = 15)
```

```{r, fig.width=15, fig.height=15}
custom_colors_hex_2 <- c("#fa6607", "#6a83d8", "#aec3b0", "#bf70bc", "#008000", "#e7c590", "#e1ceff", "#D3D3D3")
y <- spacedeconv::plot_most_abundant(spe_object, method = "cell2location",
                                     remove = c("cell2location_Cancer.Epithelial", "cell2location_Normal.Epithelial"),
                                     density = FALSE,
                                     palette = "Set2",
                                     title = "Without Epithelial",
                                     min_spot = 10,
                                     title_size = 40,
                                     font_size = 30,
                                     legend_size = 30)
y = y + 
  ggplot2::scale_fill_manual(values = custom_colors_hex_2, 
                             labels=c("B cells", "CAFs", "Endothelial", "Myeloid", "Plasmablasts", "PVL", "T cells", "Undefined"))
ggsave("~/export/suppl_2_mostAbundant_noepithelial.png", plot = y, dpi = 300, height = 15, width = 15)
```