---
title: "suppl2"
output: html_document
date: '2024-02-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spacedeconv)
library(SpatialExperiment)
library(ggplot2)
library(grid)
```

CLUSTERING ANDERSSON 
Fig supplementary
```{r}
#load the clustering results from the andersson slide
spe_expre_andersson_0.2 <- readRDS("/gpfs/gpfs1/scratch/c1041165/spacedeconv-paper-mz/spe_expre_andersson_0.2.rds")

```

```{r, fig.width=15, fig.height=15}
clus <- spacedeconv::plot_celltype(spe_expre_andersson_0.2, 
                                   cell_type = "cluster_expression_0.2",
                                   palette = "Dark2",
                                   density = F,
                                   title = "BRCA Expression \n Clustering",
                                   title_size = 40,
                                   font_size = 30,
                                   legend_size = 30)

#Save as a high-resolution PNG with specified dimensions
ggsave("/gpfs/gpfs1/scratch/c1041165/spacedeconv-paper-mz/plots_paper/suppl2/ander_clus_0.2_dark2_NEWforsuppl.png", plot = clus, dpi = 300)
```


MOST ABUNDANT ANDERSSON
Fig supplementary
```{r, clustering plot}
#load the coarse resolution results for c2l
spe_object <- readRDS("/gpfs/gpfs1/scratch/c1041165/spacedeconv-paper-mz/deconv_results_c2l_major/major_c2l_andersson.rds")

```

```{r}
#change the column names
column_names <- colnames(colData(spe_object))

# Replace "c2l" with "cell2location"
new_column_names <- sub("c2l", "cell2location", column_names)

# Set the new column names to the data frame
colnames(colData(spe_object)) <- new_column_names
```

#Coarse no removal
```{r, fig.width=15, fig.height=15}
x <- spacedeconv::plot_most_abundant(spe_object, method = "cell2location",
                                density = FALSE,
                                palette = "Accent",
                                title = "BRCA most abundant \n cell types",
                                min_spot = 10,
                                title_size = 40,
                                font_size = 30,
                                legend_size = 30)

x = x + 
  ggplot2::scale_fill_manual(values = RColorBrewer::brewer.pal(6, "Accent"), 
                             labels=c("B cell", "Cancer Epithelial", "Endothelial", "Normal Epithelial", "PVL", "T cells"))

#Save as a high-resolution PNG with specified dimensions
ggsave("/gpfs/gpfs1/scratch/c1041165/spacedeconv-paper-mz/plots_paper/suppl2/ander_mostabundant_NEWforsuppl.png", plot = x, dpi = 300)
```

#Coarse without tumor and normal epithelial
```{r, fig.width=15, fig.height=15}
y <- spacedeconv::plot_most_abundant(spe_object, method = "cell2location",
                                remove = c("cell2location_Cancer.Epithelial", "cell2location_Normal.Epithelial"),
                                density = FALSE,
                                palette = "Accent",
                                title = "BRCA most abundant \n no epithelial",
                                min_spot = 10,
                                title_size = 40,
                                font_size = 30,
                                legend_size = 30)

#change the labels manually
y = y + 
  ggplot2::scale_fill_manual(values = RColorBrewer::brewer.pal(8, "Accent"), 
                             labels=c("B cell", "CAFs", "Endothelial", "Myeloid", "Plasmablasts", "PVL", "T cells", "Undefined"))

#Save as a high-resolution PNG with specified dimensions
ggsave("/gpfs/gpfs1/scratch/c1041165/spacedeconv-paper-mz/plots_paper/suppl2/ander_mostabundant_noepithelial_NEWforsuppl.png", plot = y, dpi = 300)
```


